"""CascadeShield Results Dashboard.

Local Flask dev server that turns data/master_dataset.csv into a browsable
results view -- no more staring at runner.py's terminal output. Reproduces
the fault_type x window_type heatmaps and summary stats that used to be
generated by an ad-hoc, never-committed matplotlib script.

Run with: python app.py  (serves on http://127.0.0.1:5050)
This is a dev server only -- no auth, no WSGI, not for deployment.
"""
import base64
from io import BytesIO

import matplotlib
matplotlib.use("Agg")
from matplotlib.figure import Figure
from flask import Flask, render_template, request

import data_loader as dl

app = Flask(__name__)


def fig_to_base64(fig) -> str:
    buf = BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight")
    return base64.b64encode(buf.getvalue()).decode("ascii")


def render_heatmap(pivot, title, fmt="{:.1f}", cmap="Reds"):
    fig = Figure(figsize=(4, 3))
    ax = fig.subplots()
    im = ax.imshow(pivot.values, cmap=cmap, vmin=0)
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=20, ha="right")
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index)
    ax.set_title(title)
    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            val = pivot.values[i, j]
            text = "n/a" if pd_isna(val) else fmt.format(val)
            ax.text(j, i, text, ha="center", va="center", color="black")
    fig.colorbar(im, ax=ax, shrink=0.8)
    return fig_to_base64(fig)


def pd_isna(val):
    import math
    try:
        return math.isnan(val)
    except TypeError:
        return False


def render_distribution(count_based_df):
    fig = Figure(figsize=(5, 3.5))
    ax = fig.subplots()
    fault_types = sorted(count_based_df["fault_type"].unique())
    data = [count_based_df.loc[count_based_df["fault_type"] == ft, "blast_radius"].values for ft in fault_types]
    ax.boxplot(data, tick_labels=fault_types, showmeans=True)
    ax.set_ylabel("Blast radius (% of mesh)")
    ax.set_title("Blast radius distribution (COUNT_BASED runs)")
    return fig_to_base64(fig)


def get_current_filters():
    return {col: request.args.get(col, "") for col in dl.FILTERABLE_COLUMNS}


@app.route("/")
def index():
    df = dl.load_data()
    options = dl.get_filter_options(df)
    data_health = {
        "time_to_open_null_pct": round(df["time_to_open"].isna().mean() * 100, 1) if "time_to_open" in df else None,
        "time_to_recover_null_pct": round(df["time_to_recover"].isna().mean() * 100, 1) if "time_to_recover" in df else None,
    }
    return render_template(
        "index.html",
        total_runs=len(df),
        options=options,
        data_health=data_health,
    )


@app.route("/results")
def results():
    df = dl.load_data()
    options = dl.get_filter_options(df)
    filters = get_current_filters()
    filtered = dl.apply_filters(df, filters)

    if filtered.empty:
        return render_template(
            "results.html",
            options=options,
            filters=filters,
            empty=True,
        )

    fig1_median = render_heatmap(dl.blast_pivot(filtered, "median"), "Median blast radius (%)")
    fig1_mean = render_heatmap(dl.blast_pivot(filtered, "mean"), "Mean blast radius (%)")
    fig2 = render_heatmap(dl.trip_rate_pivot(filtered), "Breaker trip rate (%)", cmap="Blues")
    fig3 = render_distribution(dl.count_based_blast(filtered)) if not dl.count_based_blast(filtered).empty else None
    summary_table = dl.compute_summary_stats(filtered).round(4).to_html(index=False, classes="summary-table")

    return render_template(
        "results.html",
        options=options,
        filters=filters,
        empty=False,
        fig1_median=fig1_median,
        fig1_mean=fig1_mean,
        fig2=fig2,
        fig3=fig3,
        summary_table=summary_table,
        row_count=len(filtered),
    )


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5050, debug=True)
