server:
  port: 8085

spring:
  application:
    name: shared-db-service

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always
